service: servicem8-online-booking
frameworkVersion: "3"

plugins:
  - serverless-finch
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  profile: personal
  stage: dev
  region: ap-southeast-2 # set to your desired region
  logRetentionInDays: 7

  environment:
    test: ${param:test}
    apiKey: ${self:custom.secrets.apiKey} # just testing.

package:
  patterns:
    - "!secrets.yml"
    - "!client/**" # Need to check that serverless-finch still deploys the static client, but exclude from serverless.

params:
  default:
    test: bleh-${sls:stage}
  dev:
    test: blah-${sls:stage}
  prod:
    test: blay-${sls:stage}

custom:
  client: # config for serverless-finch to deploy the client to s3.
    bucketName: servicem8-online-booking
    objectHeaders:
      index.html:
        - name: Cache-Control
          value: no-cache
  serverless-offline:
    httpPort: 4000
  # Load the parameters from the secrets.yml file, which isn't included in git.
  secrets: ${file(secrets.yml):${sls:stage}}

functions:
  api:
    handler: api/index.handler
    events:
      - httpApi:
          path: /
          method: get

  test:
    handler: api/index.test
    events:
      - httpApi:
          path: /test/{id}
          method: get
